variables:
  imagetag: '$(Build.BuildId)'
  docker_image: 'nextjs-app'

trigger:
- main

pool:
  name: 'privateAksAgentPool'
stages:
- stage: Build
  displayName: "Build and Scan"
  jobs:
  - job: BuildAndScan
    displayName: "Build and Scan Docker Image"
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Private ACR'
        repository: '$(docker_image)'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/nextjsbasicapp/Dockerfile'
        tags: |
          $(imagetag)
    - task: DownloadSecureFile@1
      name: 'id_rsa'
      inputs:
        secureFile: 'id_rsa'
        retryCount: '3'
      displayName: Download Key from Pipeline to Agent
    - script: |
        echo "Transferring Docker Image to Jumpbox..."
        docker save '$(PRIVATE_ACR)/$(DOCKER_IMAGE)' | ssh -o StrictHostKeyChecking=no -i $(id_rsa.secureFilePath) appusr@$(JUMPBOX_IP) "docker load"
      displayName: "Transfer Docker Image to Jumpbox"