variables:
  imagetag: '$(Build.BuildId)'
  docker_image: 'nextjs-app'

trigger:
- main

pool:
  name: 'privateAksAgentPool'
stages:
- stage: Build
  displayName: "Build and Scan"
  jobs:
  - job: BuildAndScan
    displayName: "Build and Scan Docker Image"
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Private ACR'
        repository: '$(docker_image)'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/nextjsbasicapp/Dockerfile'
        tags: '$(PRIVATE_ACR)/$(DOCKER_IMAGE):$(imagetag)'
    
    - task: DownloadSecureFile@1
      name: 'id_rsa'
      inputs:
        secureFile: 'id_rsa'
        retryCount: '3'
      displayName: Download Key from Pipeline to Agent
    - script: |
        chmod 600 $(id_rsa.secureFilePath)
      displayName: Chmod to the key file
    - script: |
        echo "Saving file on agent..."
        echo "Image name: $(DOCKER_IMAGE):$(IMAGETAG)"
        docker save '$(PRIVATE_ACR)/$(DOCKER_IMAGE):$(IMAGETAG)' | gzip > 'webapp-$(IMAGETAG).tar.gz'
      displayName: "Saving the file on the agent machine"
    