
trigger:
- main

pool:
  name: 'privateAksAgentPool'
stages:
- stage: Build
  displayName: "Build and Scan"
  jobs:
  - job: BuildAndScan
    displayName: "Build and Scan Docker Image"
    steps:
    - script: |
        echo "Docker And Python Installation"
        sudo apt-get update
        sudo apt-get install -y docker.io python3 python3-pip
      displayName: "Installation of Docker and Python"
    - script: |
        echo "Building Docker Image..."
        docker build -t $(CONTAINER_REGISTRY)/$(DOCKER_IMAGE) .
      displayName: "Build Docker Image"