variables:
  imagetag: '$(Build.BuildId)'
  docker_image: 'nextjs-app'
trigger:
- main

pool:
  name: 'privateAksAgentPool'
stages:
- stage: Build
  displayName: "Build and Scan"
  jobs:
  - job: BuildAndScan
    displayName: "Build and Scan Docker Image"
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Private ACR'
        repository: '$(docker_image)'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/nextjsbasicapp/Dockerfile'
        tags: |
          $(imagetag)
    - task: Docker@2
      displayName: Push Image to Private ACR
      inputs:
        containerRegistry: 'Private ACR'
        repository: '$(docker_image)'
        command: 'push'
        tags: '$(imagetag)'