
trigger:
- main

pool:
  name: 'privateAksAgentPool'
stages:
- stage: Build
  displayName: "Build and Scan"
  jobs:
  - job: BuildAndScan
    displayName: "Build and Scan Docker Image"
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Private ACR'
        repository: '$(acr_name)/$(docker_image)'
        command: 'build'
        Dockerfile: '**/Dockerfile'