variables:
  imagetag: '$(Build.BuildId)'

trigger:
- main

pool:
  name: 'privateAksAgentPool'
stages:
- stage: Build
  displayName: "Build and Scan"
  jobs:
  - job: BuildAndScan
    displayName: "Build and Scan Docker Image"
    steps:
    - script: |
        echo "Temporary: Purge Docker"
        docker system prune -a --volumes -f
      displayName: Clear Docker
    - script: |
        echo "Building Docker Image..."
        docker build -t $(DOCKER_IMAGE):$(IMAGETAG) '$(Build.SourcesDirectory)/nextjsbasicapp'
      displayName: "Build Docker Image"
    - script: |
        docker images
      displayName: 'Debug Listing Images'
    - script: |
        echo "Tagging Docker Image..."
        docker tag $(DOCKER_IMAGE):$(IMAGETAG) $(PRIVATE_ACR)/$(DOCKER_IMAGE)
      displayName: "Tag Docker Image"
    - task: DownloadSecureFile@1
      name: 'id_rsa'
      inputs:
        secureFile: 'id_rsa'
        retryCount: '3'
      displayName: Download Key from Pipeline to Agent
    - script: |
        chmod 600 $(id_rsa.secureFilePath)
      displayName: Chmod to the key file

    - script: |
        echo "Saving file on agent..."
        echo "Image name: $(DOCKER_IMAGE):$(IMAGETAG)"
        docker save '$(DOCKER_IMAGE):$(IMAGETAG)' | gzip > 'webapp-$(IMAGETAG).tar.gz'
      displayName: "Saving the file on the agent machine"
      
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'Jumpbox'
        contents: 'webapp-$(IMAGETAG).tar.gz'
        readyTimeout: '20000'
      displayName: 'Copy image file'
    